French translation
Lurkars/gloomhavensecretary pull request #25
Opened 2022-09-30 13:44 UTC by Boomchil

Hi !

I used to love GHH, and once it got doomed I discovered Gloomhaven Secretary, which is better in every way ! Here is a full french translation for anyone interested, plus some typo I stumbled upon while translating it.

Note : For the "self" word, I had to duplicate it for "female" monsters, as in french we got different "self" words for male and female.

Hope you can merge it in the main repository so my french fellow can use this wonderful app ! 

Thank you

2022-09-30 15:20 UTC, Lurkars commented
First of all thank you so much for this work! I will take a deeper look later. I also have some small updates in the pipe which add some label, so would be awesome if you can migrate too then. 

Some important information about Git(Hub): if you just commit new changes to your branch of this PullRequest, the PR should update automatically!

Now for the self target, first: is the a physical french translation with differences on the card? I must say, that I don't like the idea of adding two different values for the same meaning, so maybe you can just set the label to `Sur lui-/elle-même` or `Sur lui-même/elle-même`?

Thanks again for your work!

2022-09-30 20:48 UTC, Lurkars requested changes
Thanks for this. The typos and wrong label in level are already changed in main branch from my side. Please merge latest main into your branch and update the `self` label stuff. Then I can merge this! Thank you again.

2022-09-30 20:48 UTC, Lurkars commented on data/jotl/deck/black-sludge.json
> +              "value": "selfFemale"
Would like to keep it on "self" and us single label, besides, `selfFemale` is referenced here, in label files it's `self2`.

2022-09-30 20:48 UTC, Lurkars commented on src/assets/locales/fr.json
> +      "self2": "Sur elle-même",
`self2` should be removed for a single value like `Sur lui-/elle-même`. Besides `selfFemale` is used in data and both label are missing in other languages.

2022-10-02 07:48 UTC, Boomchil commented
Hi, just dropped the SelfFemale as you want, even though it's used in the official French translation, it's used just for the Black Sludge, it'll be alright :)

2022-10-03 08:18 UTC, Lurkars commented
Thank you very much, will merge later today!

2022-10-03 11:42 UTC, merged

2022-10-06 19:27 UTC, Lurkars commented
@Boomchil Hey thanks again for your work. Do you mind if I ping you in commits, where I added some label? For now, I tried to do the french part on my own for the recent changes, but first of all a recheck will be good and I may also run into issues where I cannot adopt the text from your prev. translations.

2022-10-07 05:47 UTC, Boomchil commented
Hi 👋 

Please do, it will make my life easier as I planned to do a check every now and then to see if new labels had been added ☺️.

2022-10-07 17:12 UTC, Lurkars commented
> Hi 👋 
> 
> Please do, it will make my life easier as I planned to do a check every now and then to see if new labels had been added ☺️. 

@Boomchil did the mention in latest commit worked for you or do I need to mention you explicit here in comment?

2022-10-08 08:39 UTC, Boomchil commented
I git an email for the mention, it works fine ;)